const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event13_Act4,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundo: 0},
	{Sólido: 0},
	{pisoCentral: 0},
	{pisoEsquerdo: 0},
	{pisoDireito: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{gato1: 0},
	{bloco1: 0},
	{bloco2: 0},
	{bloco3: 0},
	{Teclado: 0},
	{arvore: 0},
	{tronco: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{imgGatoTelaInicio: 0},
	{tituloJogo: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{btnjogar: 0},
	{Mouse: 0},
	{Âncora: 0},
	{Sprite: 0},
	{vida: 0},
	{Sprite2: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite6: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Sprite7: 0},
	{Texto7: 0},
	{Texto8: 0},
	{vidas: 0}
];

self.InstanceType = {
	PlanoDeFundo: class extends self.ITiledBackgroundInstance {},
	pisoCentral: class extends self.ISpriteInstance {},
	pisoEsquerdo: class extends self.ISpriteInstance {},
	pisoDireito: class extends self.ISpriteInstance {},
	gato1: class extends self.ISpriteInstance {},
	bloco1: class extends self.ISpriteInstance {},
	bloco2: class extends self.ISpriteInstance {},
	bloco3: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	arvore: class extends self.ISpriteInstance {},
	tronco: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	imgGatoTelaInicio: class extends self.ISpriteInstance {},
	tituloJogo: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	btnjogar: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	vida: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Texto8: class extends self.ITextInstance {}
}